alias c := check
alias r := run

default: check run

check:
    prek run --all-files

run:
    zig build run

perf:
    zig build
    perf record -g ./zig-out/bin/main
    perf report

build:
    zig build --release=fast

bench:
    ./zig-out/bin/main
