[[repos]]
repo = "local"

[[repos.hooks]]
id = "ruff-check"
name = "ruff-check"
language = "system"
pass_filenames = false
entry = "ruff check --fix"

[[repos.hooks]]
id = "ruff-format"
name = "ruff-format"
language = "system"
pass_filenames = false
entry = "ruff format"

[[repos.hooks]]
id = "ty-check"
name = "ty-check"
language = "system"
pass_filenames = false
entry = "ty check"
