(import (chicken base) (chicken format) (chicken io) (chicken string) (chicken sort))
(define (parse-temp line start)
  (define len (string-length line))
  (let loop ((i start) (v 0) (neg 0))
    (if (>= i len)
      (if (= neg 1) (- v) v)
      (let ((c (string-ref line i)))
        (cond
          ((char=? c #\-) (loop (+ i 1) v 1))
          ((char=? c #\.) (loop (+ i 1) v neg))
          (else (loop (+ i 1) (+ (* v 10) (- (char->integer c) 48)) neg)))))))
(define (char-index s ch)
  (let loop ((i 0))
    (if (>= i (string-length s)) -1
        (if (char=? (string-ref s i) ch) i (loop (+ i 1))))))
(define (find-entry stats city)
  (let loop ((s stats))
    (cond ((null? s) #f)
          ((string=? (caar s) city) (cdar s))
          (else (loop (cdr s))))))
(define stats '())
(call-with-input-file "../../data/measurements.txt"
  (lambda (p)
    (let loop ((line (read-line p)))
      (when (not (eof-object? line))
        (let* ((semi (char-index line #\;))
               (city (substring line 0 semi))
               (t (parse-temp line (+ semi 1)))
               (e (find-entry stats city)))
          (if e
            (begin
              (set-car! e (min (car e) t))
              (set-car! (cdr e) (max (cadr e) t))
              (set-car! (cddr e) (+ (caddr e) t))
              (set-car! (cdddr e) (+ (car (cdddr e)) 1)))
            (set! stats (cons (cons city (list t t t 1)) stats))))
        (loop (read-line p))))))
(for-each
  (lambda (kv) (let ((city (car kv)) (e (cdr kv)))
    (format #t "~a\t~a\t~a\t~a\t~a~%" city (car e) (cadr e) (caddr e) (cadddr e))))
  (sort stats (lambda (a b) (string<? (car a) (car b)))))
