[[repos]]
repo = "local"

[[repos.hooks]]
id = "cargo-format"
name = "cargo-format"
language = "system"
pass_filenames = false
entry = "cargo fmt --check"

[[repos.hooks]]
id = "cargo-check"
name = "cargo-check"
language = "system"
pass_filenames = false
entry = "cargo clippy -- -D warnings"
