alias c := check
alias r := run

default: check run

check:
    prek run --all-files

run:
    pwsh -NoProfile -File main.ps1

build:
    @echo "nothing to build"

bench:
    pwsh -NoProfile -File main.ps1
