alias c := check
alias r := run

default: check run

check:
    prek run --all-files

run:
    deno run --allow-read main.ts

build:
    @echo "nothing to build"

bench:
    deno run --allow-read main.ts
