[[repos]]
repo = "local"

[[repos.hooks]]
id = "fmt"
name = "fmt"
language = "system"
pass_filenames = false
entry = "deno fmt --check main.ts"

[[repos.hooks]]
id = "lint"
name = "lint"
language = "system"
pass_filenames = false
entry = "deno lint main.ts"

[[repos.hooks]]
id = "check"
name = "check"
language = "system"
pass_filenames = false
entry = "deno check main.ts"
