[[repos]]
repo = "local"

[[repos.hooks]]
id = "go-fmt"
name = "go-fmt"
language = "system"
pass_filenames = false
entry = "gofmt -w main.go"

[[repos.hooks]]
id = "go-vet"
name = "go-vet"
language = "system"
pass_filenames = false
entry = "go vet main.go"
